<?php

namespace Database\Seeders;

use App\Models\University;
use Illuminate\Database\Seeder;

class UniversitySeeder extends Seeder
{
    public function run()
    {
        $universities = [
            [
                'name' => 'Tokyo International University',
                'name_japanese' => '東京国際大学',
                'established' => 1965,
                'number_of_nepali_students' => 120,
                'description' => 'Tokyo International University is a private university in Kawagoe, Saitama, Japan. Known for its English Track Program and strong international student community.',
                'address' => '1-13-1 Matoba-kita, Kawagoe',
                'city' => 'Kawagoe',
                'prefecture' => 'Saitama',
                'website' => 'https://www.tiu.ac.jp',
                'email' => 'admission@tiu.ac.jp',
                'phone' => '+81-49-232-1111',
                'type' => 'university',
                'institution_type' => 'Private',
                'tuition_fee' => 850000,
                'is_featured' => true,
            ],
            [
                'name' => 'Waseda University',
                'name_japanese' => '早稲田大学',
                'established' => 1882,
                'number_of_nepali_students' => 85,
                'description' => 'Waseda University is one of the most prestigious private universities in Japan, known for its academic excellence and global reputation.',
                'address' => '1-6-1 Nishi-Waseda, Shinjuku',
                'city' => 'Tokyo',
                'prefecture' => 'Tokyo',
                'website' => 'https://www.waseda.jp',
                'email' => 'intl-ac@list.waseda.jp',
                'phone' => '+81-3-3203-4141',
                'type' => 'university',
                'institution_type' => 'Private',
                'tuition_fee' => 1200000,
                'is_featured' => true,
            ],
            [
                'name' => 'Kyoto University',
                'name_japanese' => '京都大学',
                'established' => 1897,
                'number_of_nepali_students' => 45,
                'description' => 'Kyoto University is a national research university and one of the highest-ranked universities in Japan and Asia.',
                'address' => 'Yoshida-honmachi, Sakyo-ku',
                'city' => 'Kyoto',
                'prefecture' => 'Kyoto',
                'website' => 'https://www.kyoto-u.ac.jp',
                'email' => 'intl@mail2.adm.kyoto-u.ac.jp',
                'phone' => '+81-75-753-7531',
                'type' => 'university',
                'institution_type' => 'National',
                'tuition_fee' => 535800,
                'is_featured' => true,
            ],
            [
                'name' => 'Tokyo Japanese Language School',
                'name_japanese' => '東京日本語学校',
                'established' => 1988,
                'number_of_nepali_students' => 250,
                'description' => 'A well-established Japanese language school in Tokyo, offering comprehensive Japanese language programs for international students preparing for university or employment.',
                'address' => '2-5-10 Takadanobaba, Shinjuku',
                'city' => 'Tokyo',
                'prefecture' => 'Tokyo',
                'website' => 'https://www.tjls.ac.jp',
                'email' => 'info@tjls.ac.jp',
                'phone' => '+81-3-3371-2345',
                'type' => 'school',
                'institution_type' => 'Private',
                'tuition_fee' => 750000,
                'is_featured' => true,
            ],
            [
                'name' => 'Osaka University',
                'name_japanese' => '大阪大学',
                'established' => 1931,
                'number_of_nepali_students' => 60,
                'description' => 'Osaka University is one of Japan\'s leading national universities, known for research excellence and diverse academic programs.',
                'address' => '1-1 Yamadaoka, Suita',
                'city' => 'Suita',
                'prefecture' => 'Osaka',
                'website' => 'https://www.osaka-u.ac.jp',
                'email' => 'intl@osaka-u.ac.jp',
                'phone' => '+81-6-6879-7096',
                'type' => 'university',
                'institution_type' => 'National',
                'tuition_fee' => 535800,
                'is_featured' => false,
            ],
            [
                'name' => 'Sendai International Japanese Language School',
                'name_japanese' => '仙台国際日本語学校',
                'established' => 1995,
                'number_of_nepali_students' => 180,
                'description' => 'Located in Sendai city, this school offers quality Japanese education with lower living costs compared to Tokyo.',
                'address' => '3-2-15 Kakyoin, Aoba-ku',
                'city' => 'Sendai',
                'prefecture' => 'Miyagi',
                'website' => 'https://www.sijls.jp',
                'email' => 'admission@sijls.jp',
                'phone' => '+81-22-217-8501',
                'type' => 'school',
                'institution_type' => 'Private',
                'tuition_fee' => 680000,
                'is_featured' => false,
            ],
            [
                'name' => 'Nagoya Institute of Technology',
                'name_japanese' => '名古屋工業大学',
                'established' => 1949,
                'number_of_nepali_students' => 35,
                'description' => 'A national university specializing in engineering and technology, offering various programs in English.',
                'address' => 'Gokiso-cho, Showa-ku',
                'city' => 'Nagoya',
                'prefecture' => 'Aichi',
                'website' => 'https://www.nitech.ac.jp',
                'email' => 'intl@adm.nitech.ac.jp',
                'phone' => '+81-52-735-5083',
                'type' => 'university',
                'institution_type' => 'National',
                'tuition_fee' => 535800,
                'is_featured' => false,
            ],
            [
                'name' => 'Fukuoka Japanese Language School',
                'name_japanese' => '福岡日本語学校',
                'established' => 2002,
                'number_of_nepali_students' => 220,
                'description' => 'A popular language school in Fukuoka known for its supportive environment and strong job placement assistance.',
                'address' => '1-8-30 Hakataeki-higashi, Hakata-ku',
                'city' => 'Fukuoka',
                'prefecture' => 'Fukuoka',
                'website' => 'https://www.fjls.ac.jp',
                'email' => 'info@fjls.ac.jp',
                'phone' => '+81-92-441-0505',
                'type' => 'school',
                'institution_type' => 'Private',
                'tuition_fee' => 700000,
                'is_featured' => true,
            ],
            [
                'name' => 'Hokkaido University',
                'name_japanese' => '北海道大学',
                'established' => 1876,
                'number_of_nepali_students' => 28,
                'description' => 'One of Japan\'s oldest national universities, located in Sapporo, offering world-class education and research opportunities.',
                'address' => 'Kita 8, Nishi 5, Kita-ku',
                'city' => 'Sapporo',
                'prefecture' => 'Hokkaido',
                'website' => 'https://www.hokudai.ac.jp',
                'email' => 'intl@academic.hokudai.ac.jp',
                'phone' => '+81-11-706-8036',
                'type' => 'university',
                'institution_type' => 'National',
                'tuition_fee' => 535800,
                'is_featured' => false,
            ],
            [
                'name' => 'Tokyo Technical College',
                'name_japanese' => '東京工科専門学校',
                'established' => 1985,
                'number_of_nepali_students' => 150,
                'description' => 'A vocational school offering IT, automotive, and technical programs with strong industry connections and job placement support.',
                'address' => '2-46-1 Higashi-Ikebukuro, Toshima-ku',
                'city' => 'Tokyo',
                'prefecture' => 'Tokyo',
                'website' => 'https://www.ttc.ac.jp',
                'email' => 'admission@ttc.ac.jp',
                'phone' => '+81-3-5960-5001',
                'type' => 'vocational',
                'institution_type' => 'Private',
                'tuition_fee' => 900000,
                'is_featured' => true,
            ],
            [
                'name' => 'Kyushu University',
                'name_japanese' => '九州大学',
                'established' => 1911,
                'number_of_nepali_students' => 42,
                'description' => 'A leading national university in Fukuoka, known for engineering and scientific research.',
                'address' => '744 Motooka, Nishi-ku',
                'city' => 'Fukuoka',
                'prefecture' => 'Fukuoka',
                'website' => 'https://www.kyushu-u.ac.jp',
                'email' => 'intl@jimu.kyushu-u.ac.jp',
                'phone' => '+81-92-802-2217',
                'type' => 'university',
                'institution_type' => 'National',
                'tuition_fee' => 535800,
                'is_featured' => false,
            ],
            [
                'name' => 'Osaka Japanese Language Academy',
                'name_japanese' => '大阪日本語アカデミー',
                'established' => 1998,
                'number_of_nepali_students' => 195,
                'description' => 'A reputable Japanese language school in Osaka with excellent university placement rates and JLPT preparation courses.',
                'address' => '1-3-15 Namba, Chuo-ku',
                'city' => 'Osaka',
                'prefecture' => 'Osaka',
                'website' => 'https://www.ojla.ac.jp',
                'email' => 'info@ojla.ac.jp',
                'phone' => '+81-6-6641-1234',
                'type' => 'school',
                'institution_type' => 'Private',
                'tuition_fee' => 720000,
                'is_featured' => true,
            ],
        ];

        foreach ($universities as $university) {
            University::create($university);
        }
    }
}
